"""Add sighting and face tables

Revision ID: a36f1685be48
Revises: d99a4c5abaa2
Create Date: 2025-12-15 21:43:22.551678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a36f1685be48'
down_revision: Union[str, Sequence[str], None] = 'd99a4c5abaa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'session_type', name='unique_sighting')
    )
    op.create_index(op.f('ix_class_sightings_date'), 'class_sightings', ['date'], unique=False)
    op.create_index(op.f('ix_class_sightings_id'), 'class_sightings', ['id'], unique=False)
    op.create_table('user_faces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('encoding', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_faces_id'), 'user_faces', ['id'], unique=False)
    op.drop_column('users', 'face_encoding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face_encoding', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_faces_id'), table_name='user_faces')
    op.drop_table('user_faces')
    op.drop_index(op.f('ix_class_sightings_id'), table_name='class_sightings')
    op.drop_index(op.f('ix_class_sightings_date'), table_name='class_sightings')
    op.drop_table('class_sightings')
    # ### end Alembic commands ###
